"""Seed Knowledge Core V1.1 — full stars / palaces / life questions (DB-driven)."""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import create_engine, text

BACKEND = Path(__file__).resolve().parents[1]
ROOT = BACKEND.parent
load_dotenv(BACKEND / ".env", override=True)

VERSION = "1.1.0"


def star(
    name: str,
    category: str,
    element: str,
    yy: str,
    basic: str,
    pos: list[str],
    chal: list[str],
    career: list[str],
    risk: list[str],
    wealth: list[str],
    rel: list[str],
    stage: str,
    trad: str,
    growth: str,
) -> dict:
    return {
        "star_name": name,
        "category": category,
        "five_element": element,
        "yin_yang": yy,
        "basic_meaning": basic,
        "personality_positive": pos,
        "personality_challenge": chal,
        "career_strength": career,
        "career_risk": risk,
        "wealth_pattern": wealth,
        "relationship_pattern": rel,
        "life_stage_expression": stage,
        "traditional_description": trad,
        "growth_advice": growth,
        "ai_prompt": f"仅依据 Knowledge Core 解释「{name}」，禁止绝对预测与恐吓表述。",
        "source_reference": "Knowledge Core V1.1",
        "version": VERSION,
    }


STARS: list[dict] = [
    # 十四主星
    star("紫微", "main", "土", "阴", "统筹与中枢调度的象征。",
         ["领导力", "规划意识", "责任感"], ["控制欲偏强", "压力固执"],
         ["管理协调", "战略规划"], ["权力执念"], ["稳健经营"], ["重视边界"],
         "中年后管理与责任议题更突出。", "传统上常视为北斗主星，象征尊贵与调度。",
         "把统筹能力落到可验证的阶段性目标。"),
    star("天机", "main", "木", "阴", "思辨、谋略与变化思考的象征。",
         ["思辨", "策略", "学习力"], ["思虑过多", "执行拖延"],
         ["策划分析", "咨询研究"], ["想法多于落地"], ["研究型投入"], ["沟通理性"],
         "青年期学习与策略训练更关键。", "传统常用天机描述善谋与机变。",
         "用最小可行方案把思考转化为行动。"),
    star("太阳", "main", "火", "阳", "外显影响力与付出照耀的象征。",
         ["热情", "表达力", "服务意识"], ["过度付出", "边界模糊"],
         ["品牌传播", "教育辅导"], ["消耗过快"], ["主动分享"], ["外向连接"],
         "中年需注意能量回收。", "传统以太阳象征光明与奉献。",
         "建立休息与补给节奏。"),
    star("武曲", "main", "金", "阴", "执行、决断与专业技艺象征。",
         ["执行力", "决断", "专业深耕"], ["沟通偏硬"],
         ["技术金融", "交付运营"], ["协作摩擦"], ["技能变现"], ["直接坦率"],
         "积累期强调专业壁垒。", "传统常以武曲论财星与刚决。",
         "结果导向与协作反馈并行。"),
    star("天同", "main", "水", "阳", "安稳、享受与调和氛围的象征。",
         ["亲和", "乐观", "协调"], ["安逸惰性"],
         ["服务协调", "客户关系"], ["进取不足"], ["稳健消费"], ["温和体贴"],
         "人生阶段更重生活质量。", "传统常以天同论福与安逸。",
         "在舒适区外设置小挑战配额。"),
    star("廉贞", "main", "火", "阴", "二次性、原则与情感张力的象征。",
         ["原则感", "魅力", "抗压"], ["情绪波动", "人际张力"],
         ["法务风控", "创意表达"], ["关系消耗"], ["起伏较大"], ["激情与冲突并存"],
         "关键转折期情绪管理更重要。", "传统常以廉贞论次桃花与刚柔。",
         "用规则与复盘稳定情绪振幅。"),
    star("天府", "main", "土", "阳", "稳重守成与资源涵养的象征。",
         ["务实", "稳健", "包容"], ["偏保守"],
         ["运营管理", "流程建设"], ["错失窗口"], ["长期积累"], ["重视承诺"],
         "成长期后更重守成经营。", "传统以天府为库星。",
         "稳健基础上保留可控试错。"),
    star("太阴", "main", "水", "阴", "细腻、内敛与滋养的象征。",
         ["细腻", "洞察", "耐心"], ["敏感内耗"],
         ["研究设计", "护理服务"], ["过度操心"], ["细水长流"], ["重视情感安全"],
         "夜型节奏与内在滋养更关键。", "传统以太阴论阴柔与财荫。",
         "建立情绪边界与补给习惯。"),
    star("贪狼", "main", "木", "阳", "欲望、拓展与多元兴趣的象征。",
         ["开拓欲", "社交力", "学习欲"], ["分心多欲"],
         ["商务拓展", "创意营销"], ["目标漂移"], ["多元尝试"], ["魅力互动"],
         "青年期拓展面更广。", "传统以贪狼论欲望与桃花。",
         "用优先级清单约束欲望带宽。"),
    star("巨门", "main", "水", "阴", "口才、思辨与是非议题的象征。",
         ["表达力", "逻辑", "求真"], ["口舌争执"],
         ["传播法律", "研究评论"], ["沟通冲突"], ["信息敏感"], ["直言不讳"],
         "表达型职业阶段更突出。", "传统以巨门论暗与口舌。",
         "把直言转化为结构化沟通。"),
    star("天相", "main", "水", "阳", "辅佐、礼仪与协调支持的象征。",
         ["协作", "规范", "支持力"], ["依赖权威"],
         ["幕僚运营", "行政协调"], ["自主不足"], ["稳健配置"], ["重视礼节"],
         "中层协作角色更匹配。", "传统以天相论印星辅弼。",
         "在辅佐中练习独立判断。"),
    star("天梁", "main", "土", "阳", "荫护、清誉与解决问题的象征。",
         ["清誉", "担当", "化解力"], ["好为人师"],
         ["顾问咨询", "公益教育"], ["负担过重"], ["稳健信誉"], ["照顾他人"],
         "中年后荫护与清誉议题增强。", "传统以天梁论荫与解厄。",
         "照顾他人同时设定边界。"),
    star("七杀", "main", "金", "阴", "开创、锋芒与压力行动的象征。",
         ["魄力", "抗压", "开创"], ["冲动冲突"],
         ["开拓业务", "危机处理"], ["风险过高"], ["进取偏好"], ["独立性强"],
         "开创期冲劲更强。", "传统以七杀论将星与挑战。",
         "配套止损与复盘机制。"),
    star("破军", "main", "水", "阴", "变革、突破与推陈出新的象征。",
         ["突破力", "变革意识"], ["善始难终"],
         ["转型创新", "改革推进"], ["频繁换赛道"], ["高变动偏好"], ["节奏变化快"],
         "转型窗口期更活跃。", "传统以破军论破旧立新。",
         "用里程碑约束变革节奏。"),
    # 六吉
    star("左辅", "aux", "土", "阳", "贵人辅佐与团队助力象征。",
         ["助人", "合作"], ["过度依赖外援"],
         ["团队协作"], ["独立性不足"], ["人脉资源"], ["互助关系"],
         "贵人运随合作网络增强。", "传统以左辅为吉星辅弼。",
         "把贵人转为可互换的协作能力。"),
    star("右弼", "aux", "水", "阴", "侧面支持与协调补位象征。",
         ["灵活补位", "人际润滑"], ["迎合讨好"],
         ["协调沟通"], ["立场不清"], ["合作增益"], ["温和互动"],
         "协作阶段更易得助。", "传统以右弼为对宫辅星。",
         "补位同时保持清晰立场。"),
    star("文昌", "aux", "金", "阳", "文书、考试与表达资质象征。",
         ["学习力", "文笔"], ["纸上谈兵"],
         ["写作考试", "知识工作"], ["轻实操"], ["知识变现"], ["理性表达"],
         "求学考证期更关键。", "传统以文昌论文星科名。",
         "学以致用，连接实务反馈。"),
    star("文曲", "aux", "水", "阴", "才艺、巧思与感性表达象征。",
         ["才艺", "巧思"], ["情绪化表达"],
         ["设计艺术", "沟通创意"], ["稳定性不足"], ["创意变现"], ["感性互动"],
         "创意表达期更活跃。", "传统以文曲论文华才艺。",
         "把灵感沉淀为可交付作品。"),
    star("天魁", "aux", "火", "阳", "阳贵人与公开助力象征。",
         ["贵人缘", "正面机遇"], ["等待贵人"],
         ["公开合作"], ["主动性不足"], ["机会引入"], ["正式关系"],
         "公开场合更易遇助。", "传统以天魁为阳贵。",
         "主动经营可信专业形象。"),
    star("天钺", "aux", "火", "阴", "阴贵人与私下助力象征。",
         ["暗助", "细腻支持"], ["依赖隐助"],
         ["幕后协作"], ["暴露不足"], ["间接机会"], ["私下信任"],
         "关键节点易得暗助。", "传统以天钺为阴贵。",
         "把暗助转化为可持续关系资产。"),
    # 六煞
    star("擎羊", "sha", "金", "阳", "锋锐、摩擦与突破阻力象征。",
         ["突破力"], ["冲突急躁"],
         ["攻坚岗位"], ["人际摩擦"], ["波动"], ["言语尖锐"],
         "压力期更需克制。", "传统以擎羊为煞星刚锐。",
         "把锋芒用于解决问题而非对人。"),
    star("陀罗", "sha", "金", "阴", "拖延、纠结与粘滞课题象征。",
         ["耐心深挖"], ["拖延纠结"],
         ["深度研究"], ["决策迟缓"], ["现金流粘滞"], ["关系黏腻"],
         "整理期拖延风险升高。", "传统以陀罗论拖延纠缠。",
         "用截止时间打破粘滞。"),
    star("火星", "sha", "火", "阳", "爆发力与急躁冲动象征。",
         ["爆发执行"], ["急躁"],
         ["短平快项目"], ["冲动决策"], ["快进快出"], ["情绪激烈"],
         "高速推进期需降温。", "传统以火星论急火。",
         "决策前设置冷静窗口。"),
    star("铃星", "sha", "火", "阴", "压抑爆发与暗潮压力象征。",
         ["韧性"], ["压抑焦虑"],
         ["高压岗位"], ["情绪堆积"], ["隐忧财务"], ["闷冲突"],
         "长期压力期更需疏导。", "传统以铃星论暗火。",
         "建立规律疏导与倾诉渠道。"),
    star("地空", "sha", "火", "阳", "空想、落空与理想落差象征。",
         ["想象开脑"], ["计划落空"],
         ["创意构想"], ["落地不足"], ["理想化投入"], ["期待落差"],
         "规划期警惕空转。", "传统以地空论空亡感。",
         "每个想法配一个最小验证。"),
    star("地劫", "sha", "火", "阴", "损耗、争竞与资源流失警示象征。",
         ["危机意识"], ["消耗感"],
         ["风控意识"], ["资源损耗"], ["防守型财务"], ["关系消耗"],
         "扩张期注意损耗。", "传统以地劫论劫夺。",
         "扩张同时设定成本上限。"),
    # 其他
    star("禄存", "aux", "土", "阳", "俸禄、积蓄与稳定供给象征。",
         ["踏实积蓄"], ["保守吝啬"],
         ["稳定职业"], ["进取不足"], ["储蓄导向"], ["务实相处"],
         "积累期更偏稳健。", "传统以禄存论禄库。",
         "储蓄与适度投资并行。"),
    star("天马", "aux", "火", "阳", "变动、出行与行动加速象征。",
         ["行动力", "适应性"], ["安稳不足"],
         ["出差拓展", "移动办公"], ["漂泊感"], ["机会流动"], ["关系节奏快"],
         "外出变动期更活跃。", "传统以天马论驿马。",
         "行动加速同时保留锚点。"),
    star("红鸾", "aux", "水", "阳", "喜庆、互动与关系展开象征。",
         ["喜庆互动"], ["情绪起伏"],
         ["礼仪公关"], ["分心应酬"], ["喜庆开支"], ["关系升温"],
         "关系互动期更明显。", "传统以红鸾论喜事。",
         "互动热情配合长期经营。"),
    star("天喜", "aux", "水", "阴", "喜庆对星、社交欢愉象征。",
         ["乐观社交"], ["表面热闹"],
         ["活动组织"], ["深度不足"], ["社交消费"], ["轻松互动"],
         "社交扩展期更活跃。", "传统以天喜为红鸾对星。",
         "热闹之后做深度连接。"),
    star("孤辰", "sha", "火", "阳", "独立、疏离与独处需求象征。",
         ["独立自主"], ["疏离感"],
         ["独立作业"], ["团队融入难"], ["独自决策财务"], ["保持距离"],
         "独处需求阶段更强。", "传统以孤辰论孤独象。",
         "独立同时练习必要连接。"),
    star("寡宿", "sha", "火", "阴", "内敛、寡合与内心距离象征。",
         ["内省"], ["封闭"],
         ["研究型工作"], ["社交回避"], ["保守财务"], ["慢热关系"],
         "内省期更明显。", "传统以寡宿论寡合。",
         "保留空间也安排低压力社交。"),
]


PALACES = [
    {
        "palace_name": "命宫",
        "basic_meaning": "自我气质与选择底色",
        "life_area": "personality",
        "psychological_meaning": "自我认同与决策风格",
        "modern_interpretation": "认识我是谁、如何做选择",
        "positive_expression": "清晰自我定位",
        "challenge_expression": "把象征当命运判决",
        "development_direction": "以现实反馈校正自我模型",
        "development_advice": "每季度复盘一次关键决策模式",
        "common_questions": ["我是什么样的人？"],
        "common_user_questions": ["我适合怎样做决定？", "如何认识自己？"],
        "ai_prompt": "命宫只做自我认知，不做命运判决。",
        "version": VERSION,
    },
    {
        "palace_name": "兄弟宫",
        "basic_meaning": "同辈协作与横向关系",
        "life_area": "relationship",
        "psychological_meaning": "平辈信任与竞争",
        "modern_interpretation": "同事、朋友、合伙协作模式",
        "positive_expression": "互助协作",
        "challenge_expression": "竞争比较内耗",
        "development_direction": "建立平等互惠协作",
        "development_advice": "明确合作边界与分工",
        "common_questions": ["如何与平辈相处？"],
        "common_user_questions": ["适合合伙吗？"],
        "ai_prompt": "兄弟宫谈协作模式，不谈宿命。",
        "version": VERSION,
    },
    {
        "palace_name": "夫妻宫",
        "basic_meaning": "亲密关系与长期合作互动",
        "life_area": "relationship",
        "psychological_meaning": "依附与边界",
        "modern_interpretation": "伴侣/长期合作相处方式",
        "positive_expression": "经营与沟通",
        "challenge_expression": "投射与控制",
        "development_direction": "提升沟通与边界",
        "development_advice": "用每周复盘代替情绪摊牌",
        "common_questions": ["感情模式怎样？"],
        "common_user_questions": ["如何改善亲密关系？"],
        "ai_prompt": "禁止必婚必离。",
        "version": VERSION,
    },
    {
        "palace_name": "子女宫",
        "basic_meaning": "创造、表达与晚辈互动",
        "life_area": "family",
        "psychological_meaning": "创造力与养育角色",
        "modern_interpretation": "子女关系、作品产出与创意成果",
        "positive_expression": "创造与教导",
        "challenge_expression": "过度投射期待",
        "development_direction": "把创造欲变成可持续产出",
        "development_advice": "给创造设周期，给关系设空间",
        "common_questions": ["如何与子女相处？"],
        "common_user_questions": ["创造力如何落地？"],
        "ai_prompt": "子女宫谈创造与关系经营。",
        "version": VERSION,
    },
    {
        "palace_name": "财帛宫",
        "basic_meaning": "资源态度与价值交换",
        "life_area": "wealth",
        "psychological_meaning": "安全感与金钱信念",
        "modern_interpretation": "收入结构、理财纪律与风险偏好",
        "positive_expression": "纪律与积累",
        "challenge_expression": "保证致富幻想",
        "development_direction": "匹配风险偏好的财务节奏",
        "development_advice": "先现金流安全垫，再谈进取配置",
        "common_questions": ["如何提升收入？"],
        "common_user_questions": ["适合怎样理财？"],
        "ai_prompt": "禁止财富保证。",
        "version": VERSION,
    },
    {
        "palace_name": "疾厄宫",
        "basic_meaning": "压力负荷与身心节奏",
        "life_area": "health_rhythm",
        "psychological_meaning": "压力感知与自我照顾",
        "modern_interpretation": "作息、压力管理与能量恢复（非医学诊断）",
        "positive_expression": "觉察与调节",
        "challenge_expression": "忽视休息",
        "development_direction": "建立可持续恢复系统",
        "development_advice": "睡眠、运动、边界三件套",
        "common_questions": ["如何管理压力？"],
        "common_user_questions": ["怎样恢复能量？"],
        "ai_prompt": "禁止疾病诊断，仅生活节奏建议。",
        "version": VERSION,
    },
    {
        "palace_name": "迁移宫",
        "basic_meaning": "外部环境与变动适应",
        "life_area": "life_stage",
        "psychological_meaning": "对外安全感与适应力",
        "modern_interpretation": "外出发展、环境切换与外部机遇风格",
        "positive_expression": "适应与开拓",
        "challenge_expression": "漂泊不安",
        "development_direction": "变动中设置锚点",
        "development_advice": "外出计划配套资源与退出条件",
        "common_questions": ["适合外出发展吗？"],
        "common_user_questions": ["如何面对变化？"],
        "ai_prompt": "迁移讨论用准备度语言。",
        "version": VERSION,
    },
    {
        "palace_name": "仆役宫",
        "basic_meaning": "人际网络与协作支持系统",
        "life_area": "relationship",
        "psychological_meaning": "求助与被支持的方式",
        "modern_interpretation": "朋友、团队、客户与人脉经营",
        "positive_expression": "互惠网络",
        "challenge_expression": "一味索取或讨好",
        "development_direction": "经营可互换的支持系统",
        "development_advice": "定期维护关键关系资产",
        "common_questions": ["如何经营人脉？"],
        "common_user_questions": ["团队关系怎么处？"],
        "ai_prompt": "仆役宫谈支持系统，不谈下属宿命。",
        "version": VERSION,
    },
    {
        "palace_name": "官禄宫",
        "basic_meaning": "职业方向、社会角色与事业模式",
        "life_area": "career",
        "psychological_meaning": "成就动机与贡献方式",
        "modern_interpretation": "职业方向、社会角色、事业模式、长期发展方式",
        "positive_expression": "专业定位清晰",
        "challenge_expression": "角色焦虑",
        "development_direction": "能力变现路径设计",
        "development_advice": "把星曜象征映射为可验证能力清单",
        "common_questions": ["事业方向如何？"],
        "common_user_questions": ["适合管理还是专业？", "如何长期发展？"],
        "ai_prompt": "官禄宫谈事业模式，不谈官位必然。",
        "version": VERSION,
    },
    {
        "palace_name": "田宅宫",
        "basic_meaning": "资产配置与生活根据地",
        "life_area": "wealth",
        "psychological_meaning": "归属与安全感载体",
        "modern_interpretation": "房产、固定资产与生活基地选择",
        "positive_expression": "根据地建设",
        "challenge_expression": "过度绑定资产",
        "development_direction": "资产服务生活目标",
        "development_advice": "先明确生活场景再配置资产",
        "common_questions": ["如何看待置业？"],
        "common_user_questions": ["生活基地怎么选？"],
        "ai_prompt": "田宅宫谈资产与生活根据地。",
        "version": VERSION,
    },
    {
        "palace_name": "福德宫",
        "basic_meaning": "精神满足与内在充电",
        "life_area": "personality",
        "psychological_meaning": "幸福感来源与心理补给",
        "modern_interpretation": "兴趣、休息、意义感与压力缓冲",
        "positive_expression": "内在充盈",
        "challenge_expression": "空虚透支",
        "development_direction": "可持续兴趣与休息系统",
        "development_advice": "每周固定无产出补给时间",
        "common_questions": ["怎样更安定？"],
        "common_user_questions": ["兴趣如何滋养生活？"],
        "ai_prompt": "福德宫不做病理诊断。",
        "version": VERSION,
    },
    {
        "palace_name": "父母宫",
        "basic_meaning": "长辈关系、规则来源与学习权威",
        "life_area": "family",
        "psychological_meaning": "权威内化与价值观来源",
        "modern_interpretation": "与长辈/导师/制度的关系及学习方式",
        "positive_expression": "承接智慧",
        "challenge_expression": "权威冲突",
        "development_direction": "转化规则为自我原则",
        "development_advice": "分辨可继承价值与需更新规则",
        "common_questions": ["如何与长辈相处？"],
        "common_user_questions": ["怎样面对权威？"],
        "ai_prompt": "父母宫谈关系与学习，不做家庭宿命。",
        "version": VERSION,
    },
]


LIFE_QUESTIONS = [
    {
        "question_type": "career",
        "display_name": "事业发展",
        "question_examples": ["我的事业方向如何？", "如何长期发展？"],
        "required_palaces": ["命宫", "官禄宫", "财帛宫"],
        "required_stars": [],
        "required_patterns": [],
        "analysis_logic": "命宫人格 + 官禄事业模式 + 财帛资源态度",
        "analysis_steps": ["读取命宫主星", "读取官禄主星", "匹配格局", "输出优势注意建议"],
        "output_structure": ["traditional_basis", "strengths", "challenges", "suggestions"],
        "output_template": "事业优势/注意/建议",
        "safety_notice": "不做升职成败绝对预测。",
        "version": VERSION,
    },
    {
        "question_type": "entrepreneurship",
        "display_name": "创业选择",
        "question_examples": ["适合创业吗？", "要不要自己干？"],
        "required_palaces": ["命宫", "官禄宫", "财帛宫", "迁移宫", "福德宫"],
        "required_stars": [],
        "required_patterns": ["杀破狼", "紫府同宫"],
        "analysis_logic": "人格倾向、资源能力、风险偏好、执行模式",
        "analysis_steps": [
            "人格倾向（命宫）",
            "事业模式（官禄）",
            "资源与风险（财帛）",
            "外部环境（迁移）",
            "内在补给（福德）",
            "输出创业优势/注意/建议",
        ],
        "output_structure": ["strengths", "challenges", "suggestions"],
        "output_template": "输出创业优势、需要注意、行动建议，不做是否创业判决",
        "safety_notice": "禁止对创业做是否可行的二元断言，仅提供优势、注意与建议。",
        "version": VERSION,
    },
    {
        "question_type": "career_switch",
        "display_name": "职业转换",
        "question_examples": ["要不要转行？", "如何换赛道？"],
        "required_palaces": ["命宫", "官禄宫", "迁移宫"],
        "required_stars": [],
        "required_patterns": ["破军", "杀破狼"],
        "analysis_logic": "稳定需求 vs 变革动力",
        "analysis_steps": ["评估现有优势", "评估变动成本", "给出分阶段切换建议"],
        "output_structure": ["strengths", "challenges", "suggestions"],
        "output_template": "转换优势/风险/步骤",
        "safety_notice": "不做转行必成断言。",
        "version": VERSION,
    },
    {
        "question_type": "wealth",
        "display_name": "财富规划",
        "question_examples": ["如何规划财务？", "怎样提升收入？"],
        "required_palaces": ["财帛宫", "田宅宫", "官禄宫"],
        "required_stars": [],
        "required_patterns": [],
        "analysis_logic": "收入风格 + 资产偏好 + 事业变现",
        "analysis_steps": ["财帛态度", "田宅根据地", "事业变现路径"],
        "output_structure": ["strengths", "challenges", "suggestions"],
        "output_template": "财富优势/注意/建议",
        "safety_notice": "禁止财富保证。",
        "version": VERSION,
    },
    {
        "question_type": "relationship",
        "display_name": "感情关系",
        "question_examples": ["感情模式怎样？"],
        "required_palaces": ["夫妻宫", "福德宫", "命宫"],
        "required_stars": [],
        "required_patterns": [],
        "analysis_logic": "互动模式 + 内在需求",
        "analysis_steps": ["夫妻互动", "福德补给", "命宫自我"],
        "output_structure": ["strengths", "challenges", "suggestions"],
        "output_template": "关系优势/注意/建议",
        "safety_notice": "禁止必婚必离。",
        "version": VERSION,
    },
    {
        "question_type": "marriage",
        "display_name": "婚姻经营",
        "question_examples": ["婚姻如何经营？"],
        "required_palaces": ["夫妻宫", "福德宫", "田宅宫"],
        "required_stars": [],
        "required_patterns": [],
        "analysis_logic": "长期相处与生活根据地",
        "analysis_steps": ["相处模式", "精神补给", "生活场景"],
        "output_structure": ["strengths", "challenges", "suggestions"],
        "output_template": "经营优势/注意/建议",
        "safety_notice": "强调经营而非宿命。",
        "version": VERSION,
    },
    {
        "question_type": "study",
        "display_name": "学习考试",
        "question_examples": ["如何提升学习？", "考试怎么准备？"],
        "required_palaces": ["父母宫", "官禄宫", "命宫"],
        "required_stars": ["文昌", "文曲"],
        "required_patterns": [],
        "analysis_logic": "学习风格与能力建设",
        "analysis_steps": ["学习权威来源", "事业能力映射", "自我驱动力"],
        "output_structure": ["strengths", "challenges", "suggestions"],
        "output_template": "学习优势/注意/建议",
        "safety_notice": "禁止考试必过断言。",
        "version": VERSION,
    },
    {
        "question_type": "family",
        "display_name": "家庭关系",
        "question_examples": ["与家人如何相处？"],
        "required_palaces": ["父母宫", "子女宫", "福德宫"],
        "required_stars": [],
        "required_patterns": [],
        "analysis_logic": "长辈/晚辈角色与边界",
        "analysis_steps": ["长辈关系", "创造养育", "内在补给"],
        "output_structure": ["strengths", "challenges", "suggestions"],
        "output_template": "家庭优势/注意/建议",
        "safety_notice": "不做家庭冲突宿命论。",
        "version": VERSION,
    },
    {
        "question_type": "personality",
        "display_name": "个人成长",
        "question_examples": ["如何成长？", "怎样认识自己？"],
        "required_palaces": ["命宫", "福德宫"],
        "required_stars": [],
        "required_patterns": [],
        "analysis_logic": "自我模型 + 补给系统",
        "analysis_steps": ["命宫倾向", "福德补给", "成长建议"],
        "output_structure": ["strengths", "challenges", "suggestions"],
        "output_template": "成长优势/注意/建议",
        "safety_notice": "不做病理诊断。",
        "version": VERSION,
    },
    {
        "question_type": "life_stage",
        "display_name": "人生阶段",
        "question_examples": ["这个阶段该注意什么？", "未来如何规划？"],
        "required_palaces": ["命宫", "迁移宫", "官禄宫"],
        "required_stars": [],
        "required_patterns": [],
        "analysis_logic": "阶段主题与准备度",
        "analysis_steps": ["自我状态", "外部环境", "事业节奏", "谨慎建议"],
        "output_structure": ["traditional_basis", "strengths", "challenges", "suggestions"],
        "output_template": "阶段观察/准备建议",
        "safety_notice": "涉及未来必须谨慎表达，禁止灾难恐吓。",
        "version": VERSION,
    },
]


def main() -> None:
    from sqlalchemy import create_engine, text as sql_text

    # apply schema
    eng = create_engine(os.environ["DATABASE_URL"], pool_pre_ping=True, isolation_level="AUTOCOMMIT")
    schema = (ROOT / "database" / "knowledge_schema_v1_1.sql").read_text(encoding="utf-8")
    with eng.connect() as conn:
        for stmt in [s.strip() for s in schema.split(";") if s.strip()]:
            conn.execute(sql_text(stmt))
        print("schema v1.1 applied")

        # stars upsert
        for s in STARS:
            conn.execute(
                sql_text(
                    """
                    INSERT INTO public.stars_knowledge (
                        star_name, category, five_element, yin_yang, basic_meaning,
                        personality_positive, personality_challenge, career_strength, career_risk,
                        wealth_pattern, relationship_pattern, life_stage_expression,
                        traditional_description, growth_advice, ai_prompt, source_reference, version
                    ) VALUES (
                        :star_name, :category, :five_element, :yin_yang, :basic_meaning,
                        CAST(:personality_positive AS jsonb), CAST(:personality_challenge AS jsonb),
                        CAST(:career_strength AS jsonb), CAST(:career_risk AS jsonb),
                        CAST(:wealth_pattern AS jsonb), CAST(:relationship_pattern AS jsonb),
                        :life_stage_expression, :traditional_description, :growth_advice,
                        :ai_prompt, :source_reference, :version
                    )
                    ON CONFLICT (star_name) DO UPDATE SET
                        category=EXCLUDED.category,
                        five_element=EXCLUDED.five_element,
                        yin_yang=EXCLUDED.yin_yang,
                        basic_meaning=EXCLUDED.basic_meaning,
                        personality_positive=EXCLUDED.personality_positive,
                        personality_challenge=EXCLUDED.personality_challenge,
                        career_strength=EXCLUDED.career_strength,
                        career_risk=EXCLUDED.career_risk,
                        wealth_pattern=EXCLUDED.wealth_pattern,
                        relationship_pattern=EXCLUDED.relationship_pattern,
                        life_stage_expression=EXCLUDED.life_stage_expression,
                        traditional_description=EXCLUDED.traditional_description,
                        growth_advice=EXCLUDED.growth_advice,
                        ai_prompt=EXCLUDED.ai_prompt,
                        source_reference=EXCLUDED.source_reference,
                        version=EXCLUDED.version
                    """
                ),
                {
                    **s,
                    "personality_positive": __import__("json").dumps(s["personality_positive"], ensure_ascii=False),
                    "personality_challenge": __import__("json").dumps(s["personality_challenge"], ensure_ascii=False),
                    "career_strength": __import__("json").dumps(s["career_strength"], ensure_ascii=False),
                    "career_risk": __import__("json").dumps(s["career_risk"], ensure_ascii=False),
                    "wealth_pattern": __import__("json").dumps(s["wealth_pattern"], ensure_ascii=False),
                    "relationship_pattern": __import__("json").dumps(s["relationship_pattern"], ensure_ascii=False),
                },
            )
        print("stars upserted", len(STARS))

        for p in PALACES:
            conn.execute(
                sql_text(
                    """
                    INSERT INTO public.palace_knowledge (
                        palace_name, basic_meaning, life_area, psychological_meaning,
                        modern_interpretation, positive_expression, challenge_expression,
                        development_direction, development_advice, common_questions,
                        common_user_questions, ai_prompt, version
                    ) VALUES (
                        :palace_name, :basic_meaning, :life_area, :psychological_meaning,
                        :modern_interpretation, :positive_expression, :challenge_expression,
                        :development_direction, :development_advice,
                        CAST(:common_questions AS jsonb), CAST(:common_user_questions AS jsonb),
                        :ai_prompt, :version
                    )
                    ON CONFLICT (palace_name) DO UPDATE SET
                        basic_meaning=EXCLUDED.basic_meaning,
                        life_area=EXCLUDED.life_area,
                        psychological_meaning=EXCLUDED.psychological_meaning,
                        modern_interpretation=EXCLUDED.modern_interpretation,
                        positive_expression=EXCLUDED.positive_expression,
                        challenge_expression=EXCLUDED.challenge_expression,
                        development_direction=EXCLUDED.development_direction,
                        development_advice=EXCLUDED.development_advice,
                        common_questions=EXCLUDED.common_questions,
                        common_user_questions=EXCLUDED.common_user_questions,
                        ai_prompt=EXCLUDED.ai_prompt,
                        version=EXCLUDED.version
                    """
                ),
                {
                    **p,
                    "common_questions": __import__("json").dumps(p["common_questions"], ensure_ascii=False),
                    "common_user_questions": __import__("json").dumps(
                        p["common_user_questions"], ensure_ascii=False
                    ),
                },
            )
        print("palaces upserted", len(PALACES))

        for q in LIFE_QUESTIONS:
            conn.execute(
                sql_text(
                    """
                    INSERT INTO public.life_question_models (
                        question_type, display_name, question_examples, required_palaces,
                        required_stars, required_patterns, analysis_logic, analysis_steps,
                        output_structure, output_template, safety_notice, version
                    ) VALUES (
                        :question_type, :display_name,
                        CAST(:question_examples AS jsonb), CAST(:required_palaces AS jsonb),
                        CAST(:required_stars AS jsonb), CAST(:required_patterns AS jsonb),
                        :analysis_logic, CAST(:analysis_steps AS jsonb),
                        CAST(:output_structure AS jsonb), :output_template, :safety_notice, :version
                    )
                    ON CONFLICT (question_type) DO UPDATE SET
                        display_name=EXCLUDED.display_name,
                        question_examples=EXCLUDED.question_examples,
                        required_palaces=EXCLUDED.required_palaces,
                        required_stars=EXCLUDED.required_stars,
                        required_patterns=EXCLUDED.required_patterns,
                        analysis_logic=EXCLUDED.analysis_logic,
                        analysis_steps=EXCLUDED.analysis_steps,
                        output_structure=EXCLUDED.output_structure,
                        output_template=EXCLUDED.output_template,
                        safety_notice=EXCLUDED.safety_notice,
                        version=EXCLUDED.version
                    """
                ),
                {
                    **q,
                    "question_examples": __import__("json").dumps(q["question_examples"], ensure_ascii=False),
                    "required_palaces": __import__("json").dumps(q["required_palaces"], ensure_ascii=False),
                    "required_stars": __import__("json").dumps(q["required_stars"], ensure_ascii=False),
                    "required_patterns": __import__("json").dumps(q["required_patterns"], ensure_ascii=False),
                    "analysis_steps": __import__("json").dumps(q["analysis_steps"], ensure_ascii=False),
                    "output_structure": __import__("json").dumps(q["output_structure"], ensure_ascii=False),
                },
            )
        print("life questions upserted", len(LIFE_QUESTIONS))

        for t, label in [
            ("stars_knowledge", "stars"),
            ("palace_knowledge", "palaces"),
            ("life_question_models", "life_questions"),
        ]:
            n = conn.execute(sql_text(f"SELECT COUNT(*) FROM public.{t}")).scalar()
            print(f"COUNT {label}={n}")


if __name__ == "__main__":
    main()
