-- star_combination_rules
DELETE FROM public.star_combination_rules WHERE school = 'sanhe';

INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('紫府同宫', '["紫微","天府"]', 'main_combo', '管理能力', '资源整合', '领导型人格', '', '分析紫府同宫组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('杀破狼', '["七杀","破军","贪狼"]', 'main_combo', '开创变革', '大起大落', '行动力强', '', '分析杀破狼组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('机月同梁', '["天机","太阴","天同","天梁"]', 'main_combo', '智慧型', '服务导向', '稳定发展', '', '分析机月同梁组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('日月并明', '["太阳","太阴"]', 'main_combo', '光明磊落', '贵气十足', '公众形象佳', '', '分析日月并明组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('昌曲同宫', '["文昌","文曲"]', 'aux_combo', '才华横溢', '文笔出众', '学术优势', '', '分析昌曲同宫组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('魁钺夹命', '["天魁","天钺"]', 'aux_combo', '贵人相助', '机遇较多', '逢凶化吉', '', '分析魁钺夹命组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('禄马交驰', '["禄存","天马"]', 'aux_combo', '动中求财', '事业奔波', '财富流动', '', '分析禄马交驰组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('火铃同宫', '["火星","铃星"]', 'aux_combo', '性格急躁', '突发变动', '需注意情绪', '', '分析火铃同宫组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('羊陀夹命', '["擎羊","陀罗"]', 'aux_combo', '波折较多', '需防刑伤', '坚韧考验', '', '分析羊陀夹命组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('紫微独坐', '["紫微"]', 'main_combo', '独立领导', '自我要求高', '权威气质', '', '分析紫微独坐组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('廉贞七杀', '["廉贞","七杀"]', 'main_combo', '权力欲望', '竞争意识', '事业冲劲', '', '分析廉贞七杀组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('武曲贪狼', '["武曲","贪狼"]', 'main_combo', '财富追求', '社交能力', '多元发展', '', '分析武曲贪狼组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('天同太阴', '["天同","太阴"]', 'main_combo', '温和内敛', '感情细腻', '享受生活', '', '分析天同太阴组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('太阳化禄', '["太阳"]', 'sihua_combo', '事业机遇', '名声提升', '贵人提拔', '', '分析太阳化禄组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('太阴化科', '["太阴"]', 'sihua_combo', '名声远播', '才学显现', '温和贵人', '', '分析太阴化科组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('武曲化权', '["武曲"]', 'sihua_combo', '掌财能力', '执行力强', '事业主导', '', '分析武曲化权组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('天同化忌', '["天同"]', 'sihua_combo', '情绪困扰', '福德有损', '需调节心态', '', '分析天同化忌组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('廉贞化禄', '["廉贞"]', 'sihua_combo', '桃花财禄', '人际活跃', '创意变现', '', '分析廉贞化禄组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('破军化权', '["破军"]', 'sihua_combo', '破旧立新', '变革领导', '突破困境', '', '分析破军化权组合', 'sanhe', '2026.07.22');
INSERT INTO public.star_combination_rules (combination_name, stars, category, personality, career, wealth, relationship, ai_prompt, school, version) VALUES ('紫府朝垣', '["紫微","天府"]', 'main_combo', '格局清贵', '事业稳定', '管理天赋', '', '分析紫府朝垣组合', 'sanhe', '2026.07.22');