-- star_placement_rules
DELETE FROM public.star_placement_rules WHERE school = 'sanhe';

INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '紫微', 'self', 'forward', 0, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '天机', '紫微', 'backward', 1, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '太阳', '紫微', 'backward', 3, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '武曲', '紫微', 'backward', 4, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '天同', '紫微', 'backward', 5, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '廉贞', '紫微', 'backward', 8, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '天府', '紫微', 'opposite', 0, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '太阴', '天府', 'forward', 1, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '贪狼', '天府', 'forward', 2, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '巨门', '天府', 'forward', 3, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '天相', '天府', 'forward', 4, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '天梁', '天府', 'forward', 5, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '七杀', '天府', 'forward', 6, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('main_star', '破军', '天府', 'forward', 10, '{}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('aux_star', '左辅', '', 'lookup', 0, '{"by":"lunar_month"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('aux_star', '右弼', '', 'lookup', 0, '{"by":"lunar_month"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('aux_star', '文昌', '', 'lookup', 0, '{"by":"hour_branch"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('aux_star', '文曲', '', 'lookup', 0, '{"by":"hour_branch"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('aux_star', '天魁', '', 'lookup', 0, '{"by":"year_stem"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('aux_star', '天钺', '', 'lookup', 0, '{"by":"year_stem"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('aux_star', '禄存', '', 'lookup', 0, '{"by":"year_stem"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('sha_star', '擎羊', '', 'lookup', 0, '{"by":"year_stem"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('sha_star', '陀罗', '', 'lookup', 0, '{"by":"year_stem"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('sha_star', '火星', '', 'lookup', 0, '{"by":"year_branch_hour"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('sha_star', '铃星', '', 'lookup', 0, '{"by":"year_branch_hour"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('sha_star', '地空', '', 'lookup', 0, '{"by":"hour_branch"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('sha_star', '地劫', '', 'lookup', 0, '{"by":"hour_branch"}', 'sanhe', '2026.07.22');
INSERT INTO public.star_placement_rules (rule_type, star_name, base_star, direction, offset, condition, school, version) VALUES ('za_star', '天马', '', 'lookup', 0, '{"by":"year_branch"}', 'sanhe', '2026.07.22');