-- life_question_models seed V1.0
DELETE FROM public.life_question_models WHERE version = '1.0.0';

INSERT INTO public.life_question_models
(question_type, question_examples, required_palaces, required_stars, required_patterns,
 analysis_logic, output_template, safety_notice, version)
VALUES
('career',
 '["我的事业方向如何？","适合创业还是就业？","如何发展职业？"]'::jsonb,
 '["命宫","官禄宫","财帛宫"]'::jsonb, '[]'::jsonb, '[]'::jsonb,
 '读取命宫/官禄/财帛主星与相关格局，映射为能力倾向与赛道建议。',
 'summary|traditional_view|strengths|challenges|suggestions|risk_warning|disclaimer',
 '不做升职/创业成败的绝对预测。', '1.0.0'),
('wealth',
 '["如何提升收入？","适合怎样的理财方式？"]'::jsonb,
 '["财帛宫","田宅宫"]'::jsonb, '[]'::jsonb, '[]'::jsonb,
 '围绕财帛宫讨论资源态度与纪律，结合田宅宫看资产偏好。',
 'summary|traditional_view|strengths|challenges|suggestions|risk_warning|disclaimer',
 '禁止财富保证与稳赚表述。', '1.0.0'),
('relationship',
 '["感情模式怎样？","如何改善亲密关系？"]'::jsonb,
 '["夫妻宫","福德宫"]'::jsonb, '[]'::jsonb, '[]'::jsonb,
 '从夫妻宫看互动模式，从福德宫看内在需求与补给。',
 'summary|traditional_view|strengths|challenges|suggestions|risk_warning|disclaimer',
 '禁止必婚/必离断言。', '1.0.0'),
('family',
 '["与家人如何相处？","家庭责任如何平衡？"]'::jsonb,
 '["父母宫","子女宫","福德宫"]'::jsonb, '[]'::jsonb, '[]'::jsonb,
 '讨论家庭角色与边界，强调沟通实践。',
 'summary|traditional_view|strengths|challenges|suggestions|risk_warning|disclaimer',
 '不做家庭冲突宿命论。', '1.0.0'),
('study',
 '["适合怎样学习？","如何提升专业能力？"]'::jsonb,
 '["父母宫","官禄宫","命宫"]'::jsonb, '[]'::jsonb, '[]'::jsonb,
 '把学习风格与职业能力建设连接。',
 'summary|traditional_view|strengths|challenges|suggestions|risk_warning|disclaimer',
 '禁止考试必过断言。', '1.0.0'),
('personality',
 '["我的性格特点？","如何认识自己？"]'::jsonb,
 '["命宫","福德宫"]'::jsonb, '[]'::jsonb, '[]'::jsonb,
 '以命宫主星为主，福德宫为辅，生成自我认知画像。',
 'summary|traditional_view|strengths|challenges|suggestions|risk_warning|disclaimer',
 '不做人格病理诊断。', '1.0.0'),
('life_stage',
 '["未来如何规划？","这个阶段该注意什么？"]'::jsonb,
 '["命宫","迁移宫"]'::jsonb, '[]'::jsonb, '[]'::jsonb,
 '结合大限/流年线索（若有）讨论阶段主题与准备度。',
 'summary|traditional_view|strengths|challenges|suggestions|risk_warning|disclaimer',
 '涉及未来必须使用谨慎表达，禁止灾难恐吓。', '1.0.0');
