"""辅星杂曜知识库 V1 — 先收录常用象征星，结构统一可扩展。"""

from __future__ import annotations

from typing import Any

MINOR_STAR_DATABASE: dict[str, dict[str, Any]] = {
    "天姚": {
        "name": "天姚",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常象征桃花、魅力与情感吸引，宜结合宫位与主星观察。",
        "keywords": ["魅力", "情感吸引", "社交"],
        "strengths": ["人际吸引力倾向"],
        "challenges": ["关系边界需自觉管理"],
        "meaning": "魅力与情感吸引象征",
        "modern": "可理解为社交魅力与情感议题较突出的倾向。",
    },
    "红鸾": {
        "name": "红鸾",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常与婚恋喜庆象征相关，描述关系进入新阶段的气氛。",
        "keywords": ["关系", "喜庆", "联结"],
        "strengths": ["关系推进的契机感"],
        "challenges": ["重要决定仍需现实条件匹配"],
        "meaning": "婚恋与喜庆气氛象征",
        "modern": "可理解为亲密关系议题被激活、需要经营联结的阶段倾向。",
    },
    "天喜": {
        "name": "天喜",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常与红鸾相对，象征喜庆、人际欢愉与场合热络。",
        "keywords": ["喜庆", "欢愉", "场合"],
        "strengths": ["带动轻松氛围"],
        "challenges": ["热闹之后仍要落地承诺"],
        "meaning": "喜庆与人际欢愉象征",
        "modern": "可理解为社交场合较容易获得正向反馈的倾向。",
    },
    "孤辰": {
        "name": "孤辰",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常象征独立、疏离或独处需求，并非负面标签。",
        "keywords": ["独立", "疏离", "独处"],
        "strengths": ["自主完成任务的能力"],
        "challenges": ["协作时需主动同步信息"],
        "meaning": "独立与独处需求象征",
        "modern": "可理解为更习惯独立作业、需要私人空间的倾向。",
    },
    "寡宿": {
        "name": "寡宿",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常与孤辰并论，象征清静、少应酬或情感上的自持。",
        "keywords": ["清静", "自持", "少应酬"],
        "strengths": ["专注与边界清晰"],
        "challenges": ["重要关系需刻意维护温度"],
        "meaning": "清静自持象征",
        "modern": "可理解为社交能量有限、更珍惜深度关系的倾向。",
    },
    "华盖": {
        "name": "华盖",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常象征宗教、艺术、思想与孤高气质。",
        "keywords": ["思想", "艺术", "信仰", "孤高"],
        "strengths": ["精神世界丰富", "专业深度倾向"],
        "challenges": ["孤高时需保留协作接口"],
        "meaning": "思想艺术与精神追求象征",
        "modern": "可理解为研究、创作或精神性兴趣较突出的倾向。",
    },
    "天刑": {
        "name": "天刑",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常象征规范、纪律与是非议题，提醒程序与合规意识。",
        "keywords": ["规范", "纪律", "是非", "程序"],
        "strengths": ["规则意识", "自我约束"],
        "challenges": ["挑剔过严时关系易紧绷"],
        "meaning": "规范与纪律议题象征",
        "modern": "可理解为对规则、合规与对错较为敏感的倾向。",
    },
    "天月": {
        "name": "天月",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常与身体保养、劳逸议题相关，宜作健康管理提醒而非诊断。",
        "keywords": ["保养", "劳逸", "节律"],
        "strengths": ["对身心信号较敏感"],
        "challenges": ["高压期更需规律休息"],
        "meaning": "劳逸与保养提醒象征",
        "modern": "可理解为需要更关注作息与负荷管理的倾向（非医学判断）。",
    },
    "天马": {
        "name": "天马",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常象征走动、迁移与行动力，多用来描述动态发展气质。",
        "keywords": ["走动", "迁移", "行动", "变化"],
        "strengths": ["行动与拓展倾向", "适应环境切换"],
        "challenges": ["变动多时需稳住根基"],
        "meaning": "走动迁移与行动象征",
        "modern": "可理解为出差、调动或业务拓展较活跃的倾向。",
    },
    "天官": {
        "name": "天官",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常象征名望、职场认可与公开身份相关的正面气氛。",
        "keywords": ["名望", "认可", "职场", "公开身份"],
        "strengths": ["公开场合被看见的机会感"],
        "challenges": ["名声需与实力匹配"],
        "meaning": "名望与职场认可象征",
        "modern": "可理解为专业身份与公开认可议题较突出的倾向。",
    },
    "天福": {
        "name": "天福",
        "type": "杂曜",
        "category": "辅星杂曜",
        "traditional": "传统中常象征福气、贵人气氛与资源缓和，宜作支持性线索。",
        "keywords": ["福气", "缓和", "支持", "资源"],
        "strengths": ["遇事较易找到缓冲"],
        "challenges": ["不宜把缓和当作可懈怠的理由"],
        "meaning": "福气与资源缓和象征",
        "modern": "可理解为压力情境中较容易获得缓冲与支持的倾向。",
    },
}
